blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('add_blog/', views.add_blog, name = 'add_blog'),
    path('<int:id>/', views.blog_detail, name = 'blog_detail'),
    path('<int:id>/add_comment/', views.add_comment, name = 'add_comment'),
]

roots_blog/urls.py
from django.contrib import admin
from django.urls import path, include

from blog import views as blog_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog_views.index, name='index'),
    path('blog/about/', blog_views.about, name='about'),
    path('blog/', include(('blog.urls','blog'), namespace='blog')),
    path('blog/add_blog/', include(('blog.urls','add_blog'), namespace='add_blog')),
    path('blog_detail/<int:id>', include(('blog.urls','blog_detail'), namespace='blog_detail')),
    path('blog/<int:id>/add_comment/', include(('blog.urls','add_comment'), namespace='add_comment')),
]

blog/models.py
from django import forms
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Blog(models.Model):
    blog_title = models.CharField(max_length=200, unique=True)
    blog_content = models.TextField(blank=False)
    blog_author = models.ForeignKey(User, on_delete=models.CASCADE)
    blog_post_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.blog_title

class Comment(models.Model):
    comment_content = models.TextField(verbose_name='comment')
    comment_author = models.CharField(default='Anonymous', max_length=100)
    comment_post_date = models.DateTimeField(default=timezone.now)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')

    def __str__(self):
        return self.comment_content

blog/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Blog, Comment

class BlogForm(forms.ModelForm):
    
    # author = User.objects.all()
    # blog_author = forms.CharField(author)

    class Meta:
        model = Blog
        fields = ('blog_title',
            'blog_content',
            'blog_author',
            )
    

class CommentForm(forms.ModelForm):
    comment_content = forms.CharField(label='', widget=forms.Textarea(attrs={'rows':4,'placeholder': 'Write your comment here...'}))

    class Meta:
        model = Comment
        fields = [
            'comment_content',
        ]
    
       

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy

from .models import Blog, Comment
from .forms import BlogForm, CommentForm

def index(request):
    template = 'blog/index.html'
    blogs = Blog.objects.order_by('-blog_post_date')
    comments = Comment.objects.all()

    context = {
        'blogs': blogs,
        'comments': comments
    }
    return render(request, template, context)

def add_blog(request):
    template = 'blog/add_blog.html'

    if request.method == "POST":
        form = BlogForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('blog:index'))
    else:
        context ={
            'blog_form': BlogForm,
        }
    return render(request, template, context)


def blog_detail(request, id):
    template = 'blog/blog_detail.html'
    blog = Blog.objects.get(id=id)
    context = {
        'blog':blog
    }
    return render(request, template, context)
    
def add_comment(request, id):
    template = 'blog/add_comment.html'
    blog = get_object_or_404(Blog, id=id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.blog = blog
            comment.save()
            return HttpResponseRedirect(reverse_lazy('blog:index'))
    else:
        form = CommentForm()
        context = {
            'comment_form': form,
            'blog': blog
            }
    return render(request, template, context)

def about(request):
    template = 'blog/about.html'

    return render(request, template)

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load semanticui %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <script
    src="https://code.jquery.com/jquery-3.1.1.min.js"
    integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
    crossorigin="anonymous"></script>
    <!-- my css -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Roots Blog</title>
</head>
    <body>
        <nav>
            <div class="ui container">
            <div class="ui large inverted menu">
                <a class="item" href="{% url 'index' %}">Home</a> 
                    <!-- <li>Create New Post</li> -->
                <a class="item" href="{% url 'about' %}">About</a>
            </div>
            </div>
        </nav>
        <br>
        <br>
        
        {% block content %}
        {% endblock %}
        <br>
        <br>
        <footer>
            <div class="ui center aligned container">
                <p>Copyright &copy; Roots 2019</p>
            </div>
        </footer>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

        <!-- my js -->
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

templates/blog/about.html
{% extends 'base.html' %}
{% block content %}

<div class="ui center aligned container">
    <h2>About</h2>
    <div class="text container">
        <h3>Roots Members</h3>
        <p>Regiele Anne Gomez</p>
        <p>Cedrick Tabares</p>
        <p>Mark Nepomuceno</p>
        <p>Eujene D.C. Lamando</p>
        <p>Charles Allan Abella</p>
    </div>
</div>
{% endblock %}

templates/blog/add_blog.html
{% extends 'base.html' %}
{% load semanticui %}
{% block content %}
    <div class="ui text container">
        <h1>Create New Blog</h1>
        <form class="ui form" action="{% url 'blog:add_blog' %}" method="POST">
            
            {{ blog_form.as_p }}
            {% csrf_token %}
            <!-- <input type="submit" value="Submit"> -->
            <button class="ui primary button" type="submit">
                Save
            </button>
            <a href="{% url 'index' %}"><button class="ui negative button" type="button">
                Discard
            </button></a> 
        </form>
    </div>
{% endblock %}

templates/blog/add_comment.html
{% extends 'base.html' %}
{% load semanticui %}
{% block content %}
    
    <div class="ui text container">
        <h1 class="ui header">{{ blog.blog_title }}</h1>
        <div class="content">{{ blog.blog_content }}</div>
        <br>
        <p>Comments:</p>
        {% for comment in blog.comments.all %}
        <div class="comment">
            <br>
            <strong>{{ comment.comment_author }} said</strong>
            <p>{{ comment.comment_content }}</p>
            <div class="date">
                {{ comment.comment_post_date }}
            </div>
        </div>
        {% empty %}
            <p>No comments here yet :(</p>
        {% endfor %}


        <h3>Add comment</h3>
        <form class="ui form" action="" method="POST">
            {% render_form comment_form %}
            
            {% csrf_token %}
            <button type="submit" class="ui blue button">
                Save
            </button> 
            <a href="{% url 'index' %}">
                <button type="button" class="ui negative button" >
                    Discard
                </button>
            </a> 
        </form>
    </div>
    

{% endblock %}

templates/blog/blog_detail.html
{% extends 'base.html' %}
{% block content %}
    <div class="ui text container">
        <div class="ui large header">Blog Details</div>
    <h2> {{ blog }} </h2>
    <h4> {{ blog.blog_content }} </h4>

    {% for comment in blog.comments.all %}
        <div class="comment">
            <br>
            <strong>{{ comment.comment_author }} said</strong>
            <p>{{ comment.comment_content }}</p>
            <div class="date">
                {{ comment.comment_post_date }}
            </div>
        </div>
    {% empty %}
        <p>No comments here yet :(</p>
    {% endfor %}

    <br>
    <a href="{% url 'index' %}"> <button class="ui blue button">
        Back
    </button></a>
    </div>

    
{% endblock %}

templates/blog/index.html
{% extends 'base.html' %}
{% block content %}

<div class="ui center aligned text container"><h1 class="ui huge header">Welcome to Roots Blog</h1></div><br>

    <div class="ui container">
        <h3><a href="{% url 'blog:add_blog' %}"> Create New Blog Post</a></h3>
        {% if blogs %}
            <div class="ui three column padded relaxed grid">
                {% for blog in blogs %}
                <div class="row">
                    <div class="ui raised fluid card">
                        <div class="content">
                            <div class="header"><a href="{% url 'blog:blog_detail' id=blog.id %}">{{ blog.blog_title }}</a></div>
                            <div class="meta"><span class="date">{{ blog.blog_post_date }}</span></div>
                            <div class="description">
                                {{ blog.blog_content }}
                            </div>
                        </div>
                        <div class="content">
                            <a href="{% url 'blog:add_comment' id=blog.id %}">Comments: {{blog.comments.count}}</a>
                            <div class="right floated author">
                                by: {{ blog.blog_author }}
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>    
        {% else %}
            <h3>No blog Yet</h3>
        {% endif %}
    </div>
{% endblock %}